### ISSUE TITLE
Remove debugger

### ISSUE THREAD

**Issue by DanielCMS** [courajs/ember-recorded-history#3]
Hi there,

This is a very nice addon - a small thing: could you remove this `debugger` statement?
https://github.com/courajs/ember-recorded-history/blob/master/addon/services/recorded-history.js#L84

**Comment by courajs** [comment]
Sure, thanks for noticing it! Or, if you’d like to try opening a pull request, you can get the credit in the commit log 😁
Let me know if you’d like to do that or if I should go ahead and take care of it

**Comment by DanielCMS** [comment]
Hi again!

Sure happy to do that 😄 - but seems I do not have permission to push to this repo. So maybe you can simply go ahead and add a quick fix... Also there is another debugger statement here: https://github.com/courajs/ember-recorded-history/blob/master/addon/services/recorded-history.js#L42

**Comment by courajs** [comment]
I just released v0.2.2 which removes the debugger statements. Thanks for the bug report!
